GET http://localhost:8000

###

GET http://localhost:8000/livros

###

POST http://localhost:8000/livros
Content-Type: application/json
Accept-Language: pt

# {
#     "title": "",
#     "editor": "",
#     "price": 0.0,
#     "pages": 0,
#     "author": ""
# }
{
    "title": "O Nome do Vento",
    "editor": ,
    "price": 64.90,
    "pages": 656,
    "author": "6600c41e7d34d6e6ce254eed"
}
###


GET http://localhost:8000/livros/6600b85727c192795fdf1bbd


###
GET http://localhost:8000/livros/busca?editora=Caelum

###

PUT http://localhost:8000/livros/65fcb7663a56d7a767010caa
Content-Type: application/json
Accept-Language: pt

# {
#     "title": "",
#     "editor": "",
#     "price": 0.0,
#     "pages": 0,
#     "author": ""
# }
{
    "title": "Livro de Teste de Inclusão",
    "editor": "6600d74e3f1039cd1d612dc5",
    "price": 99.99,
    "pages": 1,
    "author": "6600c41e7d34d6e6ce254eed"
}

###

DELETE http://localhost:8000/livros/6600b85727c192795fdf1bbd

###
