GET http://localhost:8000

###

GET http://localhost:8000/autores

###

POST http://localhost:8000/autores
Content-Type: application/json
Accept-Language: pt

{

}
###

GET http://localhost:8000/autores/6600c41e7d34d6e6ce254eez


###

PUT http://localhost:8000/autores/6600c4167d34d6e6ce254eeb
Content-Type: application/json
Accept-Language: pt

{
    "name": "Naruto Uzumaki",
    "nacionality": "Japanese"
}

###

DELETE http://localhost:8000/autores/6600c4167d34d6e6ce254eeb
