GET http://localhost:8000
###

GET http://localhost:8000/autores

###

POST http://localhost:8000/autores
Content-Type: application/json
Accept-Language: pt

{
    "name": "",
    "nacionality": "Brazilian"
}
###

GET http://localhost:8000/autores/6600c4007d34d6e6ce254ee7


###

PUT http://localhost:8000/autores/6600c4007d34d6e6ce254ee7
Content-Type: application/json
Accept-Language: pt

{
    "name": "Naruto Uzumaki",
    "nacionality": "Japanese"
}

###

DELETE http://localhost:8000/autores/6600c40b7d34d6e6ce254ee9
