GET http://localhost:8000

###

GET http://localhost:8000/editora

###

POST http://localhost:8000/editora
Content-Type: application/json
Accept-Language: pt

# {
#     "name": "",
# }
{
  "name": ""
}
###


GET http://localhost:8000/editora/6600d76f3f1039cd1d612dcd


###

GET http://localhost:8000/editora/busca?nome=Agi

###
###
PUT http://localhost:8000/editora/6606178cbaac55667d0f6505
Content-Type: application/json
Accept-Language: pt

{
    "name": "Livro & CIA"
}

###


DELETE http://localhost:8000/editora/66061f15d396b829eb2d5bb3
